# nanoGPT-jax

In [1]:
with open("input.txt", "r", encoding="utf-8") as file:
    text = file.read()

In [2]:
print("length of text:", len(text))

length of text: 1115394


In [3]:
print("text:", text[:100])

text: First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [4]:
chars = sorted(set(text))
vocab_size = len(chars)
print("vocab_size:", vocab_size)
print(''.join(chars))

vocab_size: 65

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


In [5]:
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda x: [stoi[ch] for ch in x]
decode = lambda x: ''.join([itos[i] for i in x])

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [6]:
import jax
from jax import numpy as jnp
import numpy as np

data = np.array(encode(text), dtype=np.int32) # no default int64, use numpy for underlying data
print(data.shape, data.dtype)
print(data[:100])

(1115394,) int32
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59]


In [7]:
# train val split
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [8]:
block_size = 8
train_data[:block_size+1]

array([18, 47, 56, 57, 58,  1, 15, 47, 58], dtype=int32)

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context, target = x[:t+1], y[t]
    print(f"when input is {context} target is {target}")

when input is [18] target is 47
when input is [18 47] target is 56
when input is [18 47 56] target is 57
when input is [18 47 56 57] target is 58
when input is [18 47 56 57 58] target is 1
when input is [18 47 56 57 58  1] target is 15
when input is [18 47 56 57 58  1 15] target is 47
when input is [18 47 56 57 58  1 15 47] target is 58


In [10]:
rng = jax.random.PRNGKey(42)
key, subkey = jax.random.split(rng)

batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = np.random.randint(0, data.shape[0] - block_size, batch_size)
    x = jnp.stack([data[i:i+block_size] for i in ix])
    y = jnp.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch("train")
print("inputs:")
print(xb.shape)
print(xb)
print("targets:")
print(yb.shape)
print(yb)

print("-----")

for b in range(batch_size):
    for t in range(block_size):
        context, target = xb[b, :t+1], yb[b, t]
        print(f"when input is {context} target is {target}")

inputs:
(4, 8)
[[52  1 39 56 51 57  6  0]
 [48 59 42 45 43 42  1 40]
 [49 43  1 58 47 50 50  1]
 [58 53 51 40 57  8  0  0]]
targets:
(4, 8)
[[ 1 39 56 51 57  6  0 13]
 [59 42 45 43 42  1 40 63]
 [43  1 58 47 50 50  1 63]
 [53 51 40 57  8  0  0 15]]
-----
when input is [52] target is 1
when input is [52  1] target is 39
when input is [52  1 39] target is 56
when input is [52  1 39 56] target is 51
when input is [52  1 39 56 51] target is 57
when input is [52  1 39 56 51 57] target is 6
when input is [52  1 39 56 51 57  6] target is 0
when input is [52  1 39 56 51 57  6  0] target is 13
when input is [48] target is 59
when input is [48 59] target is 42
when input is [48 59 42] target is 45
when input is [48 59 42 45] target is 43
when input is [48 59 42 45 43] target is 42
when input is [48 59 42 45 43 42] target is 1
when input is [48 59 42 45 43 42  1] target is 40
when input is [48 59 42 45 43 42  1 40] target is 63
when input is [49] target is 43
when input is [49 43] target is 1
whe

In [11]:
import flax.linen as nn
import optax
from einops import rearrange
import numpy as np
from functools import partial

class BigramLanguageModel(nn.Module):
    vocab_size: int
    
    @nn.compact
    def __call__(self, idx: jnp.ndarray, targets: jnp.ndarray = None):
        logits = nn.Embed(num_embeddings=self.vocab_size, features=self.vocab_size)(idx) # (bs, block_size, 
        if targets is None:
            return logits, 0
        logits_reshaped = rearrange(logits, 'b t c -> (b t) c')
        loss = optax.softmax_cross_entropy_with_integer_labels(logits_reshaped, targets.flatten())
        return logits, jnp.mean(loss)

    def generate(self, params, subkey, idx, max_new_tokens: int = 100):
        # pad idx to max_new_tokens
        idx = jnp.pad(idx, ((0,0), (0, max_new_tokens)), mode='constant', constant_values=0)

        @jax.jit
        def step_fn(i: int, idx: jnp.ndarray, key: jnp.ndarray):
            logits, loss = self.apply(params, idx)
            logits = logits[:, i, :] # we are not using the logits from the rest of the sequence
            token = jax.random.categorical(key, logits)
            new_idx = idx.at[:, i+1].set(token)
            return new_idx
        for i in range(max_new_tokens):
            subkey, key = jax.random.split(subkey)
            idx = step_fn(i, idx, key)
        return jnp.array(idx)

m = BigramLanguageModel(vocab_size=vocab_size)
params = m.init(subkey, xb, yb)
out, loss = m.apply(params, xb, yb)
print(out.shape)
print(loss)

idx = jnp.zeros((1, 1), dtype=jnp.int32)
print(decode(np.array(m.generate(params, subkey, idx, max_new_tokens=100)[0])))

(4, 8, 65)
4.1879272

yFlSnelZW$eod&mx&hF!OYNmyFf;Z;e-peU?JgFLPeuwoMmZaYH?wgihUj?ltK

KhqBwWPBEEuiYZnQM,WtQA-fjI3z ZH3.Wq:

yFlSnelZW$eod&mx&hF!OYNmyFf;Z;e-peU?JgFLPeuwoMmZaYH?wgihUj?ltK

KhqBwWPBEEuiYZnQM,WtQA-fjI3z ZH3.Wq:


In [12]:
from timeit import default_timer as timer

optimizer = optax.adamw(1e-3)
opt_state = optimizer.init(params)

@jax.jit
def train_step(params, opt_state, xb, yb):
    def loss_fn(params):
        logits, loss = m.apply(params, xb, yb)
        return loss
    
    loss, grad = jax.value_and_grad(loss_fn)(params)
    updates, opt_state = optimizer.update(grad, opt_state, params)
    params = optax.apply_updates(params, updates)
    
    return params, opt_state, loss

start_time = timer()

for step in range(10000):
    xb, yb = get_batch("train")
    params, opt_state, loss = train_step(params, opt_state, xb, yb)
    
    if step % 2000 == 0:  # Print loss every 100 steps
        jax.block_until_ready(loss)
        print(f"Step {step}, Loss: {loss:.4f}", "Elapsed time:", timer() - start_time)
        idx = jnp.zeros((1, 1), dtype=jnp.int32)

Step 0, Loss: 4.1635 Elapsed time: 0.15869743993971497
Step 2000, Loss: 3.3745 Elapsed time: 1.1456453750142828
Step 4000, Loss: 2.8744 Elapsed time: 2.1243199419695884
Step 6000, Loss: 2.4439 Elapsed time: 3.0988453349564224
Step 8000, Loss: 2.5445 Elapsed time: 4.09691127599217


In [13]:
idx = jnp.zeros((1, 1), dtype=jnp.int32)
subkey, key = jax.random.split(subkey)
print(decode(np.array(m.generate(params, key, idx, max_new_tokens=500)[0])))


VjHot lle
Whys.
HARDUno r lPrng;'sy.
TI a s vit nclmpe d ak onerfayo s akin th,
RGandoug f at aghors
Afanend me, shav-IZG arsg ICUCUCAloudsthe gu
Ane m ahe, toat pt ohour mn
THEDe boo geore.
Y:
He th I vike inth'ethit.
Pue mihen emar thin ang ofond ut t sp n s hakQLYZig, Thithou!yindss s brod BUME-
Tongpaw,
imat thex, Hxfayos he s s m:

Ange arine'me hiknOPE:
BWhmpr conot: is TUCost GHERK:
AMalamutstharthr;
OL:
DIZGzMjourngint!
IAnf tinhou, Therinceswhingend ofenedentoure.
Toumanthee p,
AUNCINCE
